language: python
python:
  - "3.4"
install:
  - pip install yamllint
  - pip install --upgrade homeassistant
script:
  - cp travisci/secrets.yaml .
  - find . -name "*.y*ml" |xargs yamllint
  - hass --script check_config -c .