- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: !secret sslcommand

#For some reason I cant have only a part of the command secret, but the command is like this:
#"ssl-cert-check -b -c /path/to/your/cert.pem | awk '{ print $NF }'"