- alias: Checking github pages ips
  trigger:
    platform: time_pattern
    hours: '17'
    minutes: '0'
    seconds: '0'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: !secret sensor.githubipcheck
  action:
    - service: notify.slack
      data:
        message: 'github pages ip has changed'

# yamllint disable rule:line-length
# We are not allowed to put secrets in a template so the template is like this:
# "{%- if sensor.url1 !=  sensor.url2 -%} true  {%- else -%} false {%- endif -%}"
