- alias: Restart bluetooth
  trigger:
    platform: time_pattern
    hours:   '3'
    minutes: '0'
    seconds: '0'
  action:
    - service: shell_command.restart_bluetooth
    - service: notify.slack
      data:
        target: "debug"
        message: "bluetooth restarted"