- alias: Restart bluetooth
  trigger:
    platform: time
    hours:   03
    minutes: 00
    seconds: 00
  action:
    - service: shell_command.restart_bluetooth
    - service: notify.slack
      data:
        target: "debug"
        message: "bluetooth restarted"