- alias: vakantiemode_lightson
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vak_mode
        state: 'on'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.krabpaallamp_switch
        - switch.speakerlamp_switch
    - service: notify.slack
      data:
        message: 'Vakantie Mode Lights On'
        target: '#debug'

- alias: vakantiemode_lightsoff
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vak_mode
        state: 'on'
  action:
    # yamllint disable-line rule:line-length
    - delay: '{{  "00:" ~ ((range(1, 59) | random) | int)  ~ ":" ~  ((range(1, 59) | random) | int) }}'
    - service: switch.turn_off
      entity_id:
        - switch.krabpaallamp_switch
        - switch.speakerlamp_switch
    - service: notify.slack
      data:
        message: 'Vakantie Mode Lights Off'
        target: '#debug'
 

